# Generated by Django 4.2.7 on 2026-03-27 18:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="ine",
            field=models.CharField(
                blank=True,
                help_text="Identifiant National Étudiant",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="matricule",
            field=models.CharField(
                blank=True,
                help_text="Attribué par le service inscription après validation",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="journalaudit",
            name="acteur",
            field=models.CharField(
                blank=True,
                help_text="Username dénormalisé pour l'historique",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="journalaudit",
            name="details",
            field=models.JSONField(
                blank=True,
                help_text="Métadonnées JSON variables selon l'action",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journalaudit",
            name="ressource",
            field=models.CharField(
                help_text="ex: auth/login, inscription/42", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
