# Generated by Django 4.2.7 on 2026-04-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dossier", "0002_dossier_etudiant_unique_per_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossieretudiant",
            name="annee_universitaire",
            field=models.CharField(help_text="ex: 2024-2025", max_length=10),
        ),
        migrations.AlterField(
            model_name="dossieretudiant",
            name="formation",
            field=models.ForeignKey(
                help_text="Formation demandée",
                on_delete=django.db.models.deletion.PROTECT,
                to="dossier.formation",
            ),
        ),
        migrations.AlterField(
            model_name="dossieretudiant",
            name="score_completude",
            field=models.IntegerField(
                default=0, help_text="0 à 100 — calculé automatiquement"
            ),
        ),
        migrations.AlterField(
            model_name="dossieretudiant",
            name="valide_par",
            field=models.IntegerField(
                blank=True, help_text="ID de l'agent qui a validé", null=True
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="code_formation",
            field=models.CharField(
                help_text="ex: L3-INFO, M1-SI, M2-SR", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="chemin_stockage",
            field=models.CharField(
                help_text="Chemin MinIO : dossiers/{etudiant_id}/{type}/{uuid}.pdf",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="date_expiration",
            field=models.DateField(
                blank=True,
                help_text="Pour les pièces avec durée de validité",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="nom_fichier",
            field=models.CharField(
                help_text="Nom original du fichier uploadé", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="taille_fichier",
            field=models.IntegerField(
                blank=True, help_text="Taille en octets", null=True
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="type_mime",
            field=models.CharField(
                blank=True,
                help_text="application/pdf | image/jpeg | image/png",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="type_piece",
            field=models.CharField(
                choices=[
                    ("bac", "Baccalauréat"),
                    ("cni", "Carte Nationale d'Identité"),
                    ("photo", "Photo d'identité"),
                    ("diplome", "Diplôme"),
                    ("releve_notes", "Relevé de notes"),
                    ("acte_naissance", "Acte de naissance"),
                    ("autre", "Autre document"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="verifie_par",
            field=models.IntegerField(
                blank=True, help_text="ID de l'agent vérificateur", null=True
            ),
        ),
        migrations.AlterField(
            model_name="uniteenseignement",
            name="code_ue",
            field=models.CharField(help_text="ex: INF301, SI401", max_length=20),
        ),
        migrations.AlterField(
            model_name="uniteenseignement",
            name="semestre",
            field=models.IntegerField(help_text="1, 2, 3 ou 4"),
        ),
        migrations.AlterField(
            model_name="uniteenseignement",
            name="volume_horaire",
            field=models.IntegerField(
                blank=True, help_text="Heures totales", null=True
            ),
        ),
    ]
