# Generated by Django 4.2.7 on 2026-03-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapeworkflow",
            name="delai_max_heures",
            field=models.IntegerField(
                default=48, help_text="Délai max avant relance automatique"
            ),
        ),
        migrations.AlterField(
            model_name="etapeworkflow",
            name="ordre",
            field=models.IntegerField(
                help_text="1=scolarité, 2=comptabilité, 3=médical, 4=bibliothèque"
            ),
        ),
        migrations.AlterField(
            model_name="etapeworkflow",
            name="validation_service",
            field=models.ForeignKey(
                help_text="Service responsable de cette étape",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapes",
                to="inscription.validationservice",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="annee_universitaire",
            field=models.CharField(help_text="ex: 2024-2025", max_length=10),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="date_inscription",
            field=models.DateTimeField(
                blank=True, help_text="Date de validation définitive", null=True
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="dossier_id",
            field=models.IntegerField(
                blank=True, help_text="ID du dossier dans le service dossier", null=True
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="etudiant_id",
            field=models.IntegerField(
                help_text="ID de l'étudiant dans le service auth"
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="formation_id",
            field=models.IntegerField(
                help_text="ID de la formation dans le service dossier"
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="numero_matricule",
            field=models.CharField(
                blank=True,
                help_text="Attribué après validation complète",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="numero_provisoire",
            field=models.CharField(
                blank=True,
                help_text="Attribué à la préinscription",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="valide_par",
            field=models.IntegerField(
                blank=True, help_text="ID de l'utilisateur qui a validé", null=True
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="montant",
            field=models.DecimalField(
                decimal_places=2, help_text="Montant total dû", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="recu_path",
            field=models.CharField(
                blank=True, help_text="Chemin MinIO vers le reçu scanné", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="reference_paiement",
            field=models.CharField(
                blank=True,
                help_text="Référence Orange Money, numéro virement...",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="validationservice",
            name="valide_par",
            field=models.IntegerField(
                blank=True, help_text="ID de l'agent validant", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="date_fin",
            field=models.DateTimeField(
                blank=True, help_text="Rempli quand statut = termine", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="etape_courante",
            field=models.IntegerField(
                default=1, help_text="Numéro de l'étape en cours (1 à 4)"
            ),
        ),
    ]
