# Generated by Django 4.2.7 on 2026-04-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0004_paytech_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpruntLivre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etudiant_id",
                    models.IntegerField(
                        help_text="ID de l'étudiant dans le service auth"
                    ),
                ),
                (
                    "numero_inventaire",
                    models.CharField(
                        help_text="Numéro d'inventaire / code-barres du livre",
                        max_length=50,
                    ),
                ),
                ("titre_livre", models.CharField(max_length=255)),
                ("date_emprunt", models.DateField()),
                ("date_retour_prevue", models.DateField()),
                (
                    "date_retour_effective",
                    models.DateField(
                        blank=True,
                        help_text="Rempli quand le livre est rendu",
                        null=True,
                    ),
                ),
                (
                    "rendu",
                    models.BooleanField(
                        default=False, help_text="True si le livre a été rendu"
                    ),
                ),
                (
                    "enregistre_par",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de l'agent bibliothèque qui a enregistré l'emprunt",
                        null=True,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
            ],
            options={
                "db_table": "emprunt_livre",
                "ordering": ["-date_emprunt"],
            },
        ),
        migrations.CreateModel(
            name="PenaliteBibliotheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etudiant_id",
                    models.IntegerField(help_text="Dénormalisé pour requêtes rapides"),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("retard", "Retard de retour"),
                            ("deterioration", "Détérioration"),
                            ("perte", "Perte du livre"),
                        ],
                        default="retard",
                        max_length=20,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de paiement"),
                            ("payee", "Payée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "date_reglement",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de paiement ou d'annulation",
                        null=True,
                    ),
                ),
                (
                    "enregistre_par",
                    models.IntegerField(
                        blank=True, help_text="ID de l'agent bibliothèque", null=True
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "emprunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalites",
                        to="inscription.empruntlivre",
                    ),
                ),
            ],
            options={
                "db_table": "penalite_bibliotheque",
                "ordering": ["-date_creation"],
            },
        ),
    ]
