# Generated by Django 4.2.7 on 2026-04-18 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0005_add_emprunt_penalite_bibliotheque"),
    ]

    operations = [
        migrations.RenameField(
            model_name="penalitebibliotheque",
            old_name="date_reglement",
            new_name="date_paiement",
        ),
        migrations.RemoveField(
            model_name="empruntlivre",
            name="observation",
        ),
        migrations.RemoveField(
            model_name="empruntlivre",
            name="rendu",
        ),
        migrations.AddField(
            model_name="empruntlivre",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empruntlivre",
            name="note",
            field=models.TextField(
                blank=True, help_text="Observations de l'agent bibliothèque"
            ),
        ),
        migrations.AddField(
            model_name="empruntlivre",
            name="statut",
            field=models.CharField(
                choices=[
                    ("emprunte", "Emprunté"),
                    ("rendu", "Rendu"),
                    ("perdu", "Perdu"),
                ],
                default="emprunte",
                help_text="emprunte = en sa possession, rendu = restitué, perdu = déclaré perdu",
                max_length=20,
            ),
        ),
    ]
